### ISSUE TITLE
Pad section

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#1]
## Value Statement
As a **musician**
I need a **section of 16 pads ordered 4 x 4**
so that i can **trigger sounds in a drum machine for finger drumming**
I need **labeled Pads to see which Pad i use**

## Description (Text, Scribble, Wireframe, Design)
16 rectangle pads ordered in a 4 x 4 matrix
The pads are labeled (for example: Pad 1, Pad 2, ..., Pad 16)
![IMG_0145](https://user-images.githubusercontent.com/36743463/75612144-2a4d9f80-5b21-11ea-93a1-2b58943e81b9.jpg)

## Acceptance criteria
- [x] 16 Pads
- [x] Pads ordered in a 4 x 4 Matrix
- [x] Each Pad needs a visible lable
- [x] Pads react on click and 
- [x] App is allways in landscape mode

## Tasks
- [x] Create pad component
- [x] Create pad section component
- [x] Lable pads
- [x] Add click / touch logic to pads
- [x] Styling
- [ ] Test in mobile view for cellphone and tablet
