### ISSUE TITLE
BUG: no tone on iOS

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#11]

**Comment by arisslin** [comment]
## Description

There comes no sound out of the speakers of iOS devices.

## Tasks

- [ ] Test on Android devices
- [ ] Make new build and test on github pages
- [ ] Test new build on other webserver
