### ISSUE TITLE
Keyboard logic

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#16]
## Value statement
As a **musician**
I need **to trigger the sounds with a keyboard**
so that **can play the sounds on desktop or laptop without a touch screen**

## Description (Text, Scribble, Wireframe, Design)
Every pad get's triggered with it's own key on a keyboard.
Visual Feedback for the actual triggered pad

## Acceptance criteria
- [x] Every pad get's triggered with it's own key
- [ ] Visual feedback of the triggered pad on the screen

## Tasks
- [ ] Assign each pad to a key
- [ ] Add sound trigger logic
- [ ] Create logic for visual feedback
- [ ] Style visual feedback
- [ ] Testing
- [ ] Storybook for triggered pad
