### ISSUE TITLE
New mobile Layout

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#17]
## Value statement

As a **musician**
I need **a layout for mobile devices**
so that **i have a better visualisation what i am doing**

## Description (Text, Scribble, Wireframe, Design)
- Title on the right of the pads
- Display on the left of the app
- pad section near the left of the app
- Buttons to navigate through the menu
<img width="636" alt="Bildschirmfoto 2020-03-17 um 11 09 37" src="https://user-images.githubusercontent.com/36743463/76845989-1489eb00-6840-11ea-9aec-043e3b4740bd.png">
<img width="326" alt="Bildschirmfoto 2020-03-17 um 11 10 03" src="https://user-images.githubusercontent.com/36743463/76845995-194e9f00-6840-11ea-8676-663a0a5d2acd.png">

## Acceptance Criterias

- [x] Display on the left top of the app
- [x] Display shows text
- [x] Buttons under the display
- [ ] Title between display and buttons in landscape mode
- [ ] Title between pad-section and buttons in portrait mode
- [x] Pad section suqare size between title and display

## Tasks
- [x] Add Display
- [x] Add Title
- [x] Add Buttons
- [x] Style
- [x] Storybook
- [ ] Test
