### ISSUE TITLE
Pad sounds

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#2]

**Comment by arisslin** [comment]
## Value statement
As a **musician**
I need **on every pad another drum sound**
so that **I can practice my finger drumming skills**
After **I click or touch a pad the sound should be triggered and come out of the speakers**

## Description (Text, Scribble, Wireframe, Design)
- Every pad has it's own drum sound
- The sounds get triggered / played by clicking or touching a pad.
- The sounds are hearable over the speakers

## Acceptance criteria
- [ ] Every pad has it's own drum sound
- [ ] Every sound has to get triggered by click or touch on the pad
- [ ] Every sound has to come out of the speakers after triggering
- [ ] Every sound has to play from the start after get triggered
- [ ] The sound are polyphonic

## Tasks 
- [ ] Place sounds in a own folder in the project
- [ ] Put sounds in every instance of a pad component
- [ ] Create and add trigger logic for every pad
- [ ] Testing
