### ISSUE TITLE
Info page

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#27]
## Value statement
As a **musician**
I need to **see a the keyboard shortcuts**
so that **know which keys i have to press to trigger the sounds on laptop or desktop**

## Description

The keyboard layout is shown in the display component. See the attached scribbles.
<img width="634" alt="Bildschirmfoto 2020-03-17 um 12 09 47" src="https://user-images.githubusercontent.com/36743463/76850721-41420080-6848-11ea-8483-bf19fe00fb03.png">
<img width="357" alt="Bildschirmfoto 2020-03-17 um 12 09 58" src="https://user-images.githubusercontent.com/36743463/76850735-443cf100-6848-11ea-8c77-9f5a44cde77c.png">

## Acceptance criterias

- [x] Switch to info page with a button 
- [ ] The active button is to be noticed with a different color then the other ones
- [x] Title in the display shows "Keybord shortcuts"
- [x] A graphics shows the assignment of keys

## Tasks
- [ ] Create info page
- [ ] Create title
- [ ] Create keyboard graphic
- [ ] Storybook
- [ ] Style for landscape
- [ ] Style for portrait
- [ ] Test
