### ISSUE TITLE
Multitouch pads

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#3]

**Comment by arisslin** [comment]
## Value statement
As a **musician**
I need **pads which work on multitouch**
so that **I can perform realistic drum pattens where sounds get triggered polyphonic**

## Description (Text, Scribble, Wireframe, Design)
- Pads react on multitouch

## Acceptance criteria
- [ ] Pads perform on multitouch finger triggering
- [ ] Different pad sounds play polyphonic 

## Tasks
-  [ ] Add multitouch logic on pads and pad section
-  [ ] Testing
