### ISSUE TITLE
Pad volume

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#4]

**Comment by arisslin** [comment]
## Value statement
As a *musician*
I need to *adjust the volume of each drum sound*
so that *I get a realistic volume mix of the drum set when i do finger drumming*

## Description (Text, Scribble, Wireframe, Design)
- The pad sound volume ist adjustable on the mixer page
- The volume of each pad get's adjusted by a vertical fader

## Acceptance criteria
- [ ] Pad sounds change volume by moving the faders
- [ ] Volume change should be hearable for each pad

## Tasks
- [ ] Add volume adjust logic to mixer
