### ISSUE TITLE
Mixing section

### ISSUE THREAD

**Issue by arisslin** [arisslin/jsmpc#5]

**Comment by arisslin** [comment]
## Value statement
As a *musician*
I need *a mixer*
so that *I can later mix the sound of each pad*

## Description (Text, Scribble, Wireframe, Design)
- The mixer is on it's own page
- There is a button on the perform page to get to the mixer
- There is a back button to get back to the perform page
- On the perform page there are vertical channels for each pad
- Every channel has a label with the name of the channel / pad on it's bottom
- Every channel has his own volume fader

## Acceptance criteria
- [ ] The mixer is on it's own page
- [ ] Every pad has it's own mixer channel with naming label and volume fader
- [ ] It is possible to switch to the mixer page from the perform page
- [ ] It is possible to switch from the mixer page back to the perform page
- [ ] The faders are adjustable by touch events

## Tasks
- [ ] Create nav button for mixing page
- [ ] Create nav button for perform 
- [ ] Add nav switch logic
- [ ] Create mixer component
- [ ] Add mixer component to mixer page
- [ ] Styling
- [ ] Testing
